project:
  type: website
  output-dir: docs
  
website:
  title: "Alex Stapleton"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: instagram
        href: https://twitter.com/
      - icon: github
        href: https://github.com/alexstapletonns/personal
  page-footer:
    right: "Saint Carlo Acutis, Pray for Us!"
    left: "&copy; Copyright 2026, Alex Stapleton"

format:
  html:
    theme: Zephyr
    toc: true

editor: source

