project:
  type: website
  output-dir: docs
  
website:
  title: "alexstapleton.ca"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/alexstapletonns/personal
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Alex Stapleton"

format:
  html:
    theme: cerulean
    toc: true

editor: source

